export const ENV = {
  SPACE_ID: process.env.NEXT_PUBLIC_REACT_APP_CONTENTFUL_SPACE_ID ?? "",
  DELIVERY_ACCESS_TOKEN:
    process.env.NEXT_PUBLIC_REACT_APP_CONTENTFUL_DELIVERY_ACCESS_TOKEN ?? "",
  ENVIRONMENT: process.env.NEXT_PUBLIC_REACT_APP_CONTENTFUL_ENVIRONMENT ?? "",
};
